In [1]:
import pandas as pd 
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

pa = pd.read_csv('c:/temp/data/price_availability.csv');
pa.info()
pa.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4748696 entries, 0 to 4748695
Data columns (total 7 columns):
 #   Column          Dtype 
---  ------          ----- 
 0   listing_id      int64 
 1   day             object
 2   created         object
 3   available       bool  
 4   local_currency  object
 5   local_price     int64 
 6   min_nights      int64 
dtypes: bool(1), int64(3), object(3)
memory usage: 221.9+ MB


listing_id         day                       created  available  \
0     9810829  2018-12-08  2018-09-27 06:14:10.000+0000       True   
1     9810829  2018-12-08  2018-09-26 19:34:02.000+0000       True   
2    20897010  2018-12-09  2018-09-27 10:38:57.000+0000       True   
3    20897010  2018-12-09  2018-09-27 06:10:27.000+0000       True   
4    20897010  2018-12-09  2018-09-26 19:30:25.000+0000       True   

  local_currency  local_price  min_nights  
0            EUR          160           1  
1            EUR          160           1  
2            EUR          172           2  
3            EUR          172           2  
4            EUR          172           2

In [2]:
lf = pd.read_csv('c:/temp/data/listings_final.csv', sep=";");
lf.info()
lf.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Unnamed: 0                1000 non-null   int64  
 1   listing_id                1000 non-null   int64  
 2   name                      1000 non-null   object 
 3   type                      1000 non-null   object 
 4   city                      1000 non-null   object 
 5   neighborhood              935 non-null    object 
 6   latitude                  1000 non-null   float64
 7   longitude                 1000 non-null   float64
 8   person_capacity           1000 non-null   int64  
 9   beds                      1000 non-null   int64  
 10  bedrooms                  1000 non-null   int64  
 11  bathrooms                 1000 non-null   float64
 12  is_rebookable             1000 non-null   bool   
 13  is_new_listing            1000 non-null   bool   
 14  is_fully_

Unnamed: 0  listing_id                                      name  \
0           0    28581061                           La maison Clery   
1           1      661961       studio PARIS PLACE EDITH PIAF 75020   
2           2     1261705  chambre privée à louer @ paris oberkampf   
3           3     1318834            Appartement au coeur du Marais   
4           4     1677091                       Lovely & Quiet flat   

           type   city                  neighborhood   latitude  longitude  \
0  private_room  Paris             2e arrondissement  48.869292   2.348335   
1   entire_home  Paris                           NaN  48.867284   2.403255   
2  private_room  Paris                           NaN  48.867894   2.375897   
3   entire_home  Paris                    République  48.870370   2.358510   
4   entire_home  Paris  Buttes-Chaumont - Belleville  48.874149   2.373700   

   person_capacity  beds  bedrooms  bathrooms  is_rebookable  is_new_listing  \
0                1     1         1        2.0          False            True   
1                2     1         1        1.0          False           False   
2                1     1         1        1.0          False           False   
3                3     2         2        1.0          False           False   
4                2     1         1        1.0          False           False   

   is_fully_refundable  is_host_highly_rated  is_business_travel_ready  \
0                 True                 False                     False   
1                 True                  True                     False   
2                 True                  True                     False   
3                 True                 False                     False   
4                 True                  True                     False   

   pricing_weekly_factor  pricing_monthly_factor  
0                   1.00                    1.00  
1                   0.88                    0.69  
2                   1.00                    1.00  
3                   0.82                    0.48  
4                   0.95                    0.90

In [3]:
df = pa.groupby('listing_id').mean().round(2)
mergeData = lf.merge(df, left_on ='listing_id', right_on='listing_id')
mergeData.info()
mergeData.head()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 999 entries, 0 to 998
Data columns (total 22 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Unnamed: 0                999 non-null    int64  
 1   listing_id                999 non-null    int64  
 2   name                      999 non-null    object 
 3   type                      999 non-null    object 
 4   city                      999 non-null    object 
 5   neighborhood              934 non-null    object 
 6   latitude                  999 non-null    float64
 7   longitude                 999 non-null    float64
 8   person_capacity           999 non-null    int64  
 9   beds                      999 non-null    int64  
 10  bedrooms                  999 non-null    int64  
 11  bathrooms                 999 non-null    float64
 12  is_rebookable             999 non-null    bool   
 13  is_new_listing            999 non-null    bool   
 14  is_fully_r

Unnamed: 0  listing_id                                      name  \
0           0    28581061                           La maison Clery   
1           1      661961       studio PARIS PLACE EDITH PIAF 75020   
2           2     1261705  chambre privée à louer @ paris oberkampf   
3           3     1318834            Appartement au coeur du Marais   
4           4     1677091                       Lovely & Quiet flat   

           type   city                  neighborhood   latitude  longitude  \
0  private_room  Paris             2e arrondissement  48.869292   2.348335   
1   entire_home  Paris                           NaN  48.867284   2.403255   
2  private_room  Paris                           NaN  48.867894   2.375897   
3   entire_home  Paris                    République  48.870370   2.358510   
4   entire_home  Paris  Buttes-Chaumont - Belleville  48.874149   2.373700   

   person_capacity  beds  ...  is_rebookable  is_new_listing  \
0                1     1  ...          False            True   
1                2     1  ...          False           False   
2                1     1  ...          False           False   
3                3     2  ...          False           False   
4                2     1  ...          False           False   

   is_fully_refundable  is_host_highly_rated  is_business_travel_ready  \
0                 True                 False                     False   
1                 True                  True                     False   
2                 True                  True                     False   
3                 True                 False                     False   
4                 True                  True                     False   

   pricing_weekly_factor  pricing_monthly_factor  available  local_price  \
0                   1.00                    1.00       0.23        45.95   
1                   0.88                    0.69       0.03        44.47   
2                   1.00                    1.00       0.74        49.00   
3                   0.82                    0.48       0.95       165.00   
4                   0.95                    0.90       0.45        69.77   

   min_nights  
0         1.0  
1         2.0  
2         3.0  
3         2.0  
4         3.0  

[5 rows x 22 columns]

In [4]:
feature_cols = ['person_capacity', 'bathrooms', 'bedrooms']
X = mergeData.loc[:, feature_cols]
X.values

array([[1. , 2. , 1. ],
       [2. , 1. , 1. ],
       [1. , 1. , 1. ],
       ...,
       [4. , 1. , 1. ],
       [6. , 1.5, 2. ],
       [2. , 1. , 1. ]])

In [5]:
y = mergeData.local_price
y.values

array([  45.95,   44.47,   49.  ,  165.  ,   69.77,   80.56,   61.11,
        213.32,  174.03,  169.  ,  183.08,  297.76,  170.  ,   49.95,
         71.14,  160.  ,  409.55,   35.07,   62.14,  107.37,  358.12,
        115.  ,  106.71,   76.07,  302.  ,   36.59,   65.48,  153.25,
         75.88,  284.35,  219.5 ,  113.53,   93.57,  151.08,  300.  ,
        109.96,   59.08,  101.38,   67.21,   60.74,   38.  ,   92.  ,
         66.21,   79.68,   90.1 ,  170.  ,  115.75,  283.76,  144.74,
        347.67,  115.  ,  105.  ,  154.65,  380.  ,   44.17,  233.69,
        147.97,  105.  ,  163.47,  190.  ,  180.95,  128.86,  163.29,
         94.  ,   94.98,  218.96,  234.89,  300.79,   62.  ,   59.02,
         80.24,   53.  ,   92.  ,  210.88,  278.91,  165.  ,  179.67,
        105.72,   43.85,  105.16,  165.  ,  172.68,  109.  ,   42.86,
        220.  ,  136.58,  240.  ,  990.  ,  117.  ,  139.26,  196.04,
        226.  ,   69.  ,  357.44,   62.39,  145.68,  191.35,  250.  ,
        166.33,  239

In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
X_train.shape

(699, 3)

In [7]:
y_train.shape

(699,)

In [20]:
from sklearn import linear_model
from sklearn.metrics import r2_score, mean_squared_error

regr = linear_model.LinearRegression().fit(X_train, y_train)
regr

LinearRegression()

In [21]:
print('Coefficients beta_j : \n', regr.coef_)
print('Coefficients INTERCEPT beta_0 : \n', regr.intercept_)

Coefficients beta_j : 
 [33.07789742 83.12119962  8.54607816]
Coefficients INTERCEPT beta_0 : 
 -42.851074713914585


In [22]:
Y_pred = regr.predict(X_train)
len(Y_pred)

699

In [26]:
print ("Mean squared error : %.2f"
    % mean_squared_error(y_train, Y_pred))

print ('Variance score : %.2f' % r2_score(y_train, Y_pred))

Mean squared error : 22564.85
Variance score : 0.34
